[project]
name = "livinggo"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.1",
    "pytest>=9.0.2",
    "redis>=7.1.0",
    "torch>=2.9.1",
    "uvicorn>=0.40.0",
]
